// <auto-generated />
using System;
using Asas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AsasAPIs.Migrations
{
    [DbContext(typeof(AsasContext))]
    [Migration("20260525175536_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Asas.Models.Acc", b =>
                {
                    b.Property<int>("ComId")
                        .HasColumnType("int")
                        .HasColumnName("Com_id");

                    b.Property<string>("EmpId")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Emp_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<byte[]>("IV")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Iterations")
                        .HasColumnType("int");

                    b.Property<string>("Pass")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PhoneN")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("ComId", "EmpId")
                        .HasName("PK__Acc__FA34C6392624548B");

                    b.ToTable("Acc", (string)null);
                });

            modelBuilder.Entity("Asas.Models.AddE", b =>
                {
                    b.Property<int>("ComId")
                        .HasColumnType("int")
                        .HasColumnName("Com_id");

                    b.Property<string>("EmpId")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Emp_id");

                    b.Property<string>("DepId")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Dep_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("ComId", "EmpId")
                        .HasName("PK__AddE__FA34C6393A67D366");

                    b.ToTable("AddE", (string)null);
                });

            modelBuilder.Entity("Asas.Models.Company", b =>
                {
                    b.Property<int>("ComId")
                        .HasColumnType("int")
                        .HasColumnName("Com_id");

                    b.Property<DateTime>("DateOfEnd")
                        .HasColumnType("datetime")
                        .HasColumnName("Date_of_end");

                    b.Property<string>("EmpId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Emp_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("ComId")
                        .HasName("PK__Company__D85724E45D221B33");

                    b.ToTable("Company", (string)null);
                });

            modelBuilder.Entity("Asas.Models.Dep", b =>
                {
                    b.Property<int>("ComId")
                        .HasColumnType("int")
                        .HasColumnName("Com_id");

                    b.Property<string>("DepId")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Dep_id");

                    b.Property<string>("DepN")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Dep_N");

                    b.Property<string>("EmpId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Emp_id");

                    b.HasKey("ComId", "DepId")
                        .HasName("PK__Dep__9895A0F1FF9E6E83");

                    b.ToTable("Dep", (string)null);
                });

            modelBuilder.Entity("Asas.Models.Issue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("issue");
                });

            modelBuilder.Entity("Asas.Models.Acc", b =>
                {
                    b.HasOne("Asas.Models.AddE", "AddE")
                        .WithOne("Acc")
                        .HasForeignKey("Asas.Models.Acc", "ComId", "EmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("A");

                    b.Navigation("AddE");
                });

            modelBuilder.Entity("Asas.Models.AddE", b =>
                {
                    b.HasOne("Asas.Models.Dep", "Dep")
                        .WithMany("AddEs")
                        .HasForeignKey("ComId", "EmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Dep_to_AddE");

                    b.Navigation("Dep");
                });

            modelBuilder.Entity("Asas.Models.AddE", b =>
                {
                    b.Navigation("Acc");
                });

            modelBuilder.Entity("Asas.Models.Dep", b =>
                {
                    b.Navigation("AddEs");
                });
#pragma warning restore 612, 618
        }
    }
}
