@AsasAPIs_HostAddress =https://localhost:7000
GET {{AsasAPIs_HostAddress}}/Home/
Accept: application/json
###
@AsasAPIs_HostAddress = https://localhost:7000

POST {{AsasAPIs_HostAddress}}/Home/
Content-Type: application/json

{
 
}
